name: Playwright Tests
on:
  push:
    branches: [ main ]
jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.24.0-focal
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - run: npx playwright test
      - uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
